[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/google/go-github"
  revision = "fe267204ab6dc819efe645730b03eb44cbca91f1"

[[constraint]]
  name = "github.com/mattermost/mattermost-server"
  version = "~5.6.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.2.0"

[[constraint]]
  name = "github.com/ktrysmt/go-bitbucket"
  version = "0.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/wbrefvem/go-bitbucket"

[[constraint]]
  name = "github.com/go-playground/webhooks"
  version = "4.1.1"
